# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea7fd8b75c8eaf7d3cbe4f39c52dc85f88cf8e2c55974091f4d8d8907b2c7cada9e5a1ac0daa468bf9a228e5078411a8101dbd4a80e3a6b8ef5bf40bdc7b13aa

test:
  secret_key_base: 4bbb449d5c8f035ad18854a5f6847f8c097750e21b5aec6965bc79e3480b06451f4e635de21acf56af89b91ec2100c0896bbe1b7f5e26722ddada6862d30c82c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
